- name: install nginx and run
  hosts: web
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: starting nginx
    ansible.builtin.service:
      name: nginx
      state: started