- name: create ec2 through ansible
  hosts: local
  connection: local
  vars:
    sg_id: "sg-001753742e64eaea2"
    subnet_id: "subnet-01d01e08a40b72067"
    ami_id: "ami-09c813fb71547fc4f"
    region: us-east-1
    zone: "daws81s.online"
    instances:
    - mysql
    - backend
    - frontend
      
  tasks:
  - name: creating  ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      region: "{{ region }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: getting the ec2-instances information after creating
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"      

  - name: ansible creating route53
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }} . {{ zone }}"
      type: A
      ttl: 1
      value: item.instances[0].private_ip_address
      wait: true 
      override: true
    loop: "{{ ec2_instances . results }}"                     