- name: creating the expense user
  hosts: local
  connection: local
  tasks:
    - name: printing the ansible facts
      ansible.builtin.debug:
        msg: "{{ansible_facts}}"
    
    - name: checking whether user exists or not
      ansible.builtin.command: id expense
      register: USER
      ignore_errors: true

    - name: printing the user information
      ansible.builtin.debug:
        msg: "user information:{{USER}}"
