- name: installing packages using loops
  hosts: local
  connection: local
  become: true
  tasks:
    - name: install all the packages at once
      ansible.builtin.package:
        name: {{ item }}
        state: installed
      loop:
        nginx
        git
        mysql
        httpd