- name: install nginx and run
  hosts: web
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed
        become: true
    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes