- name: variables to print
  hosts: web
  vars:
    course: "Devops with Aws"
    duration: "120 Hrs"
    trainer: "sivakumar reddy"
  tasks:
    - name: print the variables
      ansible.builtin.debug
        msg: "I am learning {{course}} the course duration is {{duration}} and trainer is {{trainer}}"