- name: variables from command line
  hosts: web
  tasks:
    - name: print the information from command line
      ansible.builtin.debug:
        msg: "Iam learning {{course}} duration is {{duration}}"
