- name: variables from prompt
  hosts: web
  vars_prompt:
    - name: course
      prompt: enter the name of the course
    - name: duration
      prompt: enter the duration of the course
    - name: trainer
      prompt: enter the trainer name
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "HI Iam learning {{course}} duration is {{duration}} trainer is {{trainer}}"